import type { Product, Review, TeamMember, Order, Customer } from './types';

const IMG = (id: string, w = 400, h = 400) =>
  `https://images.unsplash.com/${id}?w=${w}&h=${h}&fit=crop&auto=format`;

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Truffes Chocolat Noir 72%',
    category: 'chocolats',
    price: 8450,
    image: IMG('photo-1596350351182-c2ce5b74a758'),
    rating: 4.8,
    reviewCount: 124,
    badge: 'nouveau',
    inStock: true,
    description: 'Nos truffes artisanales au chocolat noir 72% fondent en bouche. Chaque truffe est roulée à la main dans du cacao pur en poudre pour une expérience intense et soyeuse.',
    ingredients: 'Chocolat noir 72%, crème fraîche, beurre, cacao en poudre',
    allergens: 'Lait, peut contenir des traces de noix',
    points: 13,
  },
  {
    id: 2,
    name: 'Mendiant Lyonnais',
    category: 'chocolats',
    price: 5600,
    image: IMG('photo-1676080801076-21406293720a'),
    rating: 4.6,
    reviewCount: 89,
    badge: 'populaire',
    inStock: true,
    description: "Disques de chocolat belge garnis de fruits secs et d'éclats de noisettes torréfiées. Un classique revisité avec amour par notre équipe.",
    ingredients: 'Chocolat belge 55%, amandes, noisettes, raisins secs, orange confite',
    allergens: 'Fruits à coque, lait',
    points: 9,
  },
  {
    id: 3,
    name: 'Rocher Caramel Maison',
    category: 'chocolats',
    price: 7800,
    originalPrice: 9800,
    image: IMG('photo-1676080811961-4e90b60c7b68'),
    rating: 4.9,
    reviewCount: 203,
    badge: 'promo',
    inStock: true,
    description: 'Cœur caramel coulant enrobé de chocolat au lait et de noisettes concassées. La signature gourmande de Bombo.',
    ingredients: 'Chocolat au lait 40%, caramel beurre salé, noisettes, feuilletine',
    allergens: 'Lait, fruits à coque, gluten',
    points: 12,
  },
  {
    id: 4,
    name: 'Tablette Éclat de Sel',
    category: 'chocolats',
    price: 6500,
    image: IMG('photo-1631580692193-2402c46a6e83'),
    rating: 4.5,
    reviewCount: 67,
    inStock: true,
    description: "Tablette de chocolat noir parsemée de fleur de sel de Guérande. Le mariage parfait entre l'amertume du cacao et la minéralité du sel.",
    ingredients: 'Chocolat noir 68%, fleur de sel de Guérande',
    allergens: 'Lait, peut contenir des traces de noix',
    points: 10,
  },
  {
    id: 5,
    name: 'Oursons Gélifiés Géants',
    category: 'bonbons',
    price: 4500,
    image: IMG('photo-1693028846892-347cb82cc080'),
    rating: 4.7,
    reviewCount: 312,
    badge: 'populaire',
    inStock: true,
    description: 'Des oursons gélifiés XXL aux saveurs de fruits authentiques. Moelleux, fruités et absolument irrésistibles pour petits et grands.',
    ingredients: 'Glucose, sucre, gélatine de bœuf, arômes naturels de fruits',
    allergens: 'Peut contenir du gluten',
    points: 7,
  },
  {
    id: 6,
    name: 'Mix Acidulés Rainbow',
    category: 'bonbons',
    price: 4900,
    image: IMG('photo-1599599377756-6c2a54da71d4'),
    rating: 4.4,
    reviewCount: 45,
    badge: 'nouveau',
    inStock: true,
    description: 'Un mélange explosif de bonbons acidulés aux couleurs arc-en-ciel. Chaque bouchée est une surprise gustative qui pétille sur la langue.',
    ingredients: 'Sucre, sirop de glucose, acide citrique, colorants naturels',
    allergens: 'Peut contenir des traces de lait et de gluten',
    points: 8,
  },
  {
    id: 7,
    name: 'Réglisses Torsadées',
    category: 'bonbons',
    price: 3900,
    image: IMG('photo-1599599429032-bc4c3fc132bc'),
    rating: 4.2,
    reviewCount: 78,
    inStock: true,
    description: "Réglisses artisanales tressées à l'ancienne. Un goût authentique et prononcé de vraie réglisse noire, pour les amateurs de caractère.",
    ingredients: 'Farine de blé, extrait de réglisse, sucre, amidon de maïs',
    allergens: 'Gluten',
    points: 6,
  },
  {
    id: 8,
    name: 'Guimauves Arc-en-ciel',
    category: 'bonbons',
    price: 4300,
    originalPrice: 5850,
    image: IMG('photo-1596350351182-c2ce5b74a758'),
    rating: 4.6,
    reviewCount: 156,
    badge: 'promo',
    inStock: true,
    description: 'Guimauves soufflées et colorées aux arômes de fruits. Ultra-légères, elles fondent comme un nuage. Parfaites à griller aussi !',
    ingredients: 'Sucre, sirop de glucose, gélatine, arômes naturels, colorants végétaux',
    allergens: 'Peut contenir des traces de lait',
    points: 7,
  },
  {
    id: 9,
    name: 'Sucettes Fruits Exotiques',
    category: 'sucettes',
    price: 3200,
    image: IMG('photo-1631580692193-2402c46a6e83'),
    rating: 4.3,
    reviewCount: 34,
    badge: 'nouveau',
    inStock: true,
    description: 'Sucettes artisanales aux arômes de mangue, passion et ananas. Couleurs vives et goûts intenses pour un voyage tropical.',
    ingredients: 'Sucre, sirop de glucose, acide citrique, arômes naturels de fruits tropicaux',
    allergens: 'Aucun allergène majeur',
    points: 5,
  },
  {
    id: 10,
    name: 'Sucette Caramel Beurre Salé',
    category: 'sucettes',
    price: 2550,
    image: IMG('photo-1676080801076-21406293720a'),
    rating: 4.8,
    reviewCount: 445,
    badge: 'populaire',
    inStock: true,
    description: 'La sucette préférée des Bretons ! Caramel beurre salé coulé dans un moule arrondi, sur bâton de bois naturel. Un best-seller absolu.',
    ingredients: 'Sucre, crème, beurre demi-sel (lait), sel de Guérande',
    allergens: 'Lait',
    points: 4,
  },
  {
    id: 11,
    name: 'Sucette Géante Surprise',
    category: 'sucettes',
    price: 4300,
    image: IMG('photo-1693028846892-347cb82cc080'),
    rating: 4.5,
    reviewCount: 89,
    inStock: true,
    description: 'Une sucette XXL en spirale multicolore. Chaque couche dévoile une saveur différente : fraise, vanille, myrtille, pomme verte.',
    ingredients: 'Sucre, sirop de glucose, arômes naturels, colorants végétaux',
    allergens: 'Aucun allergène majeur',
    points: 7,
  },
  {
    id: 12,
    name: 'Macaron Framboise & Rose',
    category: 'gateaux',
    price: 1650,
    image: IMG('photo-1596350351182-c2ce5b74a758'),
    rating: 4.9,
    reviewCount: 567,
    badge: 'populaire',
    inStock: true,
    description: "Macaron délicat aux coques légères et ganache framboise parfumée à l'eau de rose. La quintessence de la pâtisserie française.",
    ingredients: "Poudre d'amande, sucre glace, blanc d'œuf, framboise, eau de rose",
    allergens: 'Fruits à coque (amandes), œufs',
    points: 3,
  },
  {
    id: 13,
    name: 'Financier Pistache Matcha',
    category: 'gateaux',
    price: 1900,
    originalPrice: 2550,
    image: IMG('photo-1676080811961-4e90b60c7b68'),
    rating: 4.7,
    reviewCount: 123,
    badge: 'promo',
    inStock: true,
    description: 'Financier moelleux aux poudres de pistache et de matcha japonais. Une alliance inattendue et sophistiquée aux notes douces et végétales.',
    ingredients: "Beurre noisette, poudre d'amande, pistache, matcha, blanc d'œuf",
    allergens: 'Fruits à coque, œufs, lait, gluten',
    points: 3,
  },
  {
    id: 14,
    name: 'Tarte Caramel Fleur de Sel',
    category: 'gateaux',
    price: 12400,
    image: IMG('photo-1599599377756-6c2a54da71d4'),
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
    description: 'Tarte entière avec pâte sablée maison, caramel onctueux et couche fine de ganache au chocolat noir. Finition fleur de sel. Pour 6 personnes.',
    ingredients: 'Farine, beurre, sucre, crème, chocolat 68%, fleur de sel',
    allergens: 'Gluten, lait, œufs',
    points: 19,
  },
  {
    id: 15,
    name: 'Coffret Découverte Bombo',
    category: 'coffrets',
    price: 18400,
    originalPrice: 23000,
    image: IMG('photo-1631580692193-2402c46a6e83'),
    rating: 4.9,
    reviewCount: 234,
    badge: 'promo',
    inStock: true,
    description: "25 pièces sélectionnées parmi nos meilleures créations : truffes, bonbons, macarons, guimauves. Idéal pour découvrir l'univers Bombo ou offrir.",
    ingredients: 'Assortiment varié — voir détail sur emballage',
    allergens: 'Lait, œufs, gluten, fruits à coque',
    points: 28,
  },
  {
    id: 16,
    name: 'Coffret Saint-Valentin',
    category: 'coffrets',
    price: 29500,
    image: IMG('photo-1693028846892-347cb82cc080'),
    rating: 4.8,
    reviewCount: 167,
    badge: 'nouveau',
    inStock: false,
    description: "Boîte coeur en velours rouge avec 30 pièces raffinées : ganaches à la rose, pralinés en cœur, fraises enrobées. Le cadeau parfait de l'amour.",
    ingredients: 'Assortiment premium — voir détail sur emballage',
    allergens: 'Lait, œufs, gluten, fruits à coque',
    points: 45,
  },
];

export const REVIEWS: Review[] = [
  {
    id: 1,
    author: 'Marie T.',
    avatar: 'https://i.pravatar.cc/80?img=47',
    rating: 5,
    text: "Les truffes au chocolat noir sont absolument divines ! Elles fondent en bouche et le cacao pur est d'une qualité exceptionnelle. Je recommande les yeux fermés.",
    date: '14 mai 2025',
  },
  {
    id: 2,
    author: 'Lucas M.',
    avatar: 'https://i.pravatar.cc/80?img=12',
    rating: 5,
    text: "Livraison ultra-rapide et emballage soigné comme un vrai cadeau. Les guimauves arc-en-ciel ont fait l'unanimité à la maison. On reviendra c'est sûr !",
    date: '8 mai 2025',
  },
  {
    id: 3,
    author: 'Chloé R.',
    avatar: 'https://i.pravatar.cc/80?img=32',
    rating: 5,
    text: "Le coffret découverte était parfait pour mon anniversaire. 25 pièces d'exception, toutes plus délicieuses les unes que les autres. Bombo, c'est la magie en boîte !",
    date: '2 mai 2025',
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 1,
    name: 'Sophie Martin',
    role: 'Fondatrice & Chef Pâtissière',
    avatar: 'https://i.pravatar.cc/150?img=47',
    quote: "\"Je mets mon cœur dans chaque bonbon. C'est ma façon de dire je t'aime au monde entier !\"",
  },
  {
    id: 2,
    name: 'Lucas Dubois',
    role: 'Maître Chocolatier',
    avatar: 'https://i.pravatar.cc/150?img=12',
    quote: '"Le chocolat est un langage universel. Je parle couramment chocolat depuis 15 ans."',
  },
  {
    id: 3,
    name: 'Emma Petit',
    role: 'Responsable Commandes',
    avatar: 'https://i.pravatar.cc/150?img=32',
    quote: "\"Chaque commande part avec un sourire. Je m'assure que votre bonheur arrive intact.\"",
  },
  {
    id: 4,
    name: 'Thomas Bernard',
    role: 'Designer & Créatif',
    avatar: 'https://i.pravatar.cc/150?img=68',
    quote: '"Les yeux mangent avant la bouche. Je crée la magie visuelle de Bombo."',
  },
];

export const ORDERS: Order[] = [
  { id: '#BOM-2451', date: '14 mai 2025', status: 'Livré', total: 25200, items: 3 },
  { id: '#BOM-2389', date: '28 avr. 2025', status: 'Livré', total: 15000, items: 2 },
  { id: '#BOM-2310', date: '10 avr. 2025', status: 'Livré', total: 37900, items: 5 },
];

export const CUSTOMERS: Customer[] = [
  { id: 1, name: 'Marie Durand', email: 'marie.d@email.fr', orders: 12, points: 840, level: 'Chocolat', lastOrder: '14 mai 2025', avatar: 'https://i.pravatar.cc/40?img=47' },
  { id: 2, name: 'Lucas Martin', email: 'l.martin@email.fr', orders: 8, points: 520, level: 'Sucre', lastOrder: '12 mai 2025', avatar: 'https://i.pravatar.cc/40?img=12' },
  { id: 3, name: 'Emma Lefebvre', email: 'emma.l@email.fr', orders: 24, points: 1850, level: 'VIP', lastOrder: '11 mai 2025', avatar: 'https://i.pravatar.cc/40?img=32' },
  { id: 4, name: 'Thomas Petit', email: 't.petit@email.fr', orders: 3, points: 180, level: 'Caramel', lastOrder: '5 mai 2025', avatar: 'https://i.pravatar.cc/40?img=68' },
  { id: 5, name: 'Chloé Robert', email: 'chloe.r@email.fr', orders: 1, points: 45, level: 'Caramel', lastOrder: '18 mars 2025', avatar: 'https://i.pravatar.cc/40?img=25', inactive: true },
  { id: 6, name: 'Antoine Bernard', email: 'a.bernard@email.fr', orders: 15, points: 1120, level: 'Chocolat', lastOrder: '9 mai 2025', avatar: 'https://i.pravatar.cc/40?img=60' },
];

export const SALES_DATA = [
  { day: 'Lun', ventes: 210000, commandes: 18 },
  { day: 'Mar', ventes: 315000, commandes: 26 },
  { day: 'Mer', ventes: 256000, commandes: 22 },
  { day: 'Jeu', ventes: 407000, commandes: 35 },
  { day: 'Ven', ventes: 558000, commandes: 48 },
  { day: 'Sam', ventes: 813000, commandes: 67 },
  { day: 'Dim', ventes: 512000, commandes: 42 },
];

export const CATEGORIES = [
  { key: 'chocolats' as const, label: 'Chocolats' },
  { key: 'bonbons' as const, label: 'Bonbons' },
  { key: 'sucettes' as const, label: 'Sucettes' },
  { key: 'gateaux' as const, label: 'Gâteaux' },
  { key: 'coffrets' as const, label: 'Coffrets' },
];
